# Generated by Django 5.0.6 on 2024-10-31 10:50

import common.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(max_length=8)),
            ],
            options={
                'verbose_name': 'Available Times for Appointments',
                'verbose_name_plural': 'Available Times for Appointments',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
            ],
            options={
                'verbose_name': 'Week Days Available for Appointments',
                'verbose_name_plural': 'Week Days Available for Appointments',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=255)),
                ('appointment_date', models.DateField()),
                ('appointment_created_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('token', models.CharField(default=common.utils.generate_unique_token, max_length=100, unique=True)),
                ('token_expiry_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.appointmenttime')),
            ],
        ),
        migrations.AddField(
            model_name='appointmenttime',
            name='week_days',
            field=models.ManyToManyField(to='appointments.weekday'),
        ),
    ]
